/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-22 06:37:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.projectResources;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ListUI_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ\" crossorigin=\"anonymous\">\r\n");
      out.write("<style>\r\n");
      out.write("    .carousel-inner img {\r\n");
      out.write("      margin: 0rem 3rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .row>div {\r\n");
      out.write("      border: 1px solid black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .col-1>.btn {\r\n");
      out.write("      margin: 0px 3px;\r\n");
      out.write("      padding: 3px;\r\n");
      out.write("      width: 100px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #main-menu>.nav-item>.nav-link.active {\r\n");
      out.write("      background-color: #5cb85c;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      /* 선택된 링크 텍스트 색상 */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #main-menu>.nav-item>.nav-link {\r\n");
      out.write("      color: #5cb85c;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <div class=\"row gx-0\">\r\n");
      out.write("        <div class=\"col-md-10\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col\">\r\n");
      out.write("                <div id=\"carouselExampleControls\" class=\"carousel slide\" style=\"background-color: lightblue;\">\r\n");
      out.write("                  <div class=\"carousel-inner\">\r\n");
      out.write("                    <div class=\"carousel-item text-center active\">\r\n");
      out.write("                      <a href=\"#\"><img class=\"img-fluid\" src=\"img/계란.png\" style=\"width: 10rem; height: 10rem;\"></a>\r\n");
      out.write("                      <a href=\"#\"><img class=\"img-fluid\" src=\"img/고기.png\" style=\" width: 10rem; height: 10rem;\"></a>\r\n");
      out.write("                      <a href=\"#\"><img class=\"img-fluid\" src=\"img/새우.png\" style=\"width: 10rem; height: 10rem;\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"carousel-item text-center\">\r\n");
      out.write("                      <a href=\"#\"><img class=\"img-fluid\" src=\"img/야채.png\" style=\"width: 10rem; height: 10rem;\"></a>\r\n");
      out.write("                      <a href=\"#\"><img class=\"img-fluid\" src=\"img/육가공.png\" style=\"width: 10rem; height: 10rem;\"></a>\r\n");
      out.write("                      <a href=\"#\"><img class=\"img-fluid\" src=\"img/치킨.png\" style=\"width: 10rem; height: 10rem;\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"carousel-item text-center\">\r\n");
      out.write("                      <a href=\"#\"><img class=\"img-fluid\" src=\"img/페스트푸드.png\" style=\"width: 10rem; height: 10rem;\"></a>\r\n");
      out.write("                      <a href=\"#\"><img class=\"img-fluid\" src=\"img/해물.png\" style=\"width: 10rem; height: 10rem;\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleControls\"\r\n");
      out.write("                    data-bs-slide=\"prev\">\r\n");
      out.write("                    <img class=\"img-fluid\" src=\"img/왼쪽화살표.png\">\r\n");
      out.write("                    <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("                  </button>\r\n");
      out.write("\r\n");
      out.write("                  <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleControls\"\r\n");
      out.write("                    data-bs-slide=\"next\">\r\n");
      out.write("                    <img class=\"img-fluid\" src=\"img/오른쪽화살표.png\">\r\n");
      out.write("                    <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("                  </button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-1 d-flex align-items-center\">\r\n");
      out.write("                <button class=\"btn btn-success btn-block\">자바스크립트 </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-1 d-flex align-items-center\">\r\n");
      out.write("                <button class=\"btn btn-success btn-block\">JSP </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-1 d-flex align-items-center\">\r\n");
      out.write("                <button class=\"btn btn-success btn-block\">또는 </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-1 d-flex align-items-center\">\r\n");
      out.write("                <button class=\"btn btn-success btn-block\">자바스크립트 </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-1\">\r\n");
      out.write("                <button class=\"btn btn-success btn-block\">데이터 받아서추가가능 </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-1\">\r\n");
      out.write("                <button class=\"btn btn-success btn-block\">데이터 받아서추가가능 </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-1\">\r\n");
      out.write("                <button class=\"btn btn-success btn-block\">데이터 받아서추가가능 </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-1\">\r\n");
      out.write("                <button class=\"btn btn-success btn-block\">데이터 받아서추가가능 </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-1\">\r\n");
      out.write("                <button class=\"btn btn-success btn-block\">데이터 받아서추가가능 </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-1\">\r\n");
      out.write("                <button class=\"btn btn-success btn-block\">데이터 받아서추가가능 </button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-12\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-1\">\r\n");
      out.write("                      < </div>\r\n");
      out.write("                        <div class=\"col-10\">\r\n");
      out.write("                          조회수\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-1\">\r\n");
      out.write("                          >\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("      \r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                      <div class=\"col-12\">\r\n");
      out.write("                        <div>게시물 1번</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("      \r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                      <div class=\"col-12\">\r\n");
      out.write("                        <div>게시물 2번</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                      <div class=\"col-12\">\r\n");
      out.write("                        <div>게시물 3번</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("      \r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-2\">\r\n");
      out.write("          <h1>순위 페이지</h1>\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-1\">\r\n");
      out.write("                < </div>\r\n");
      out.write("                  <div class=\"col-10\">\r\n");
      out.write("                    조회수\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-1\">\r\n");
      out.write("                    >\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                  <div>게시물 1번</div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                  <div>게시물 2번</div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                  <div>게시물 3번</div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  </body>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
