/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-20 09:49:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Storage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>헬스인을 위한 요리 레시피</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function validateForm() {\r\n");
      out.write("    var id = document.forms[\"signup\"][\"id\"].value.trim();\r\n");
      out.write("    var pw = document.forms[\"signup\"][\"pw\"].value.trim();\r\n");
      out.write("    var name = document.forms[\"signup\"][\"name\"].value.trim();\r\n");
      out.write("    var nickname = document.forms[\"signup\"][\"nickname\"].value.trim();\r\n");
      out.write("    var email = document.forms[\"signup\"][\"email\"].value.trim();\r\n");
      out.write("    var address = document.forms[\"signup\"][\"address\"].value.trim();\r\n");
      out.write("    var phone = document.forms[\"signup\"][\"phone\"].value.trim();\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    if (id == \"\" || pw == \"\" || name == \"\" || nickname == \"\" || email == \"\" || address == \"\" || phone == \"\") {\r\n");
      out.write("        alert(\"공란이 있습니다. 모두 채워주세요.\");\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("function idCheck(){\r\n");
      out.write("   window.open(\"IdCheckForm.jsp\",\"idwin\",\"width=400, height=350\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("   body{text-align: center;background-color:lightgoldenrodyellow;}\r\n");
      out.write("   h2{border:2px solid;width:300px;height:40px;margin:auto;background-color:white;}\r\n");
      out.write("   .form-box{border:2px solid;width:300px;height:400px;margin:auto;background-color:white;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <h2>회원가입 화면</h2><div>");
      out.print(session.getAttribute("check") );
      out.write("</div>\r\n");
      out.write("   <form name=\"signup\" action=\"emailPro.jsp\" method=\"post\" onsubmit=\"return validateForm()\">\r\n");
      out.write("      <div class=\"form-box\"><br>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("         ＊ID:       <input type=\"text\" name=\"id\" placeholder=\"아이디를 입력하세요\" value=\"");
      out.print(session.getAttribute("id"));
      out.write("\"/>\r\n");
      out.write("         <input type=\"button\" value=\"ID중복확인\" onclick=\"idCheck()\">\r\n");
      out.write("         <br><br>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("         *PW:       <input type=\"password\" name=\"pw\" placeholder=\"비밀번호를 입력하세요\" value=\"");
      out.print(session.getAttribute("pw"));
      out.write("\"/><br><br>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("         *Name:     <input type=\"text\" name=\"name\" placeholder=\"이름을 입력하세요\" value=\"");
      out.print(session.getAttribute("name"));
      out.write("\"/><br><br>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("         *NickName: <input type=\"text\" name=\"nickname\" placeholder=\"닉네임을 입력하세요\" value=\"");
      out.print(session.getAttribute("nickname"));
      out.write("\"/><br><br>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("         *Email:    <input type=\"text\" name=\"email\" placeholder=\"이메일을 입력하세요\" value=\"");
      out.print(session.getAttribute("email"));
      out.write("\"/><br><br>\r\n");
      out.write("         ");
if(session.getAttribute("email")==null){
            
         }else{
         
      out.write("\r\n");
      out.write("         \r\n");
      out.write("         인증번호 입력:<input type=\"text\" name=\"random\" placeholder=\"주소를 입력하세요\"/><br><br>\r\n");
      out.write("         <button type=\"submit\">인증버튼</button>\r\n");
      out.write("         \r\n");
      out.write("         ");
} 
      out.write("\r\n");
      out.write("         <button type=\"submit\">이메일보내기</button>\r\n");
      out.write("         \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("<!--       <div class=\"form-group\"> -->\r\n");
      out.write("<!--          *Address:  <input type=\"text\" name=\"address\" placeholder=\"주소를 입력하세요\"/><br><br> -->\r\n");
      out.write("<!--       </div> -->\r\n");
      out.write("<!--       <div class=\"form-group\"> -->\r\n");
      out.write("<!--          *Phone:    <input type=\"text\" name=\"phone\" placeholder=\"전화번호를 입력하세요\"/> -->\r\n");
      out.write("<!--       </div> -->\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <input type=\"submit\" value=\"회원가입\"/></div>\r\n");
      out.write("   </form> \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
